### ISSUE TITLE
events page is not displaying summerhack

### ISSUE THREAD

**Issue by DevelopmentHF** [cissa-unimelb/cissa_website#26]
<img width="1470" alt="Screen Shot 2023-02-02 at 4 45 52 pm" src="https://user-images.githubusercontent.com/93821760/216242010-1c4d7be9-0e9e-4f79-b951-82379be06c27.png">

**Comment by thebowenfeng** [comment]
The Airtable embed will only show events that hasn't started yet, since summerhack has already started, that is probably the reason why it isn't showing up. 

You can view past events (i.e events that has already begun) by scrolling to the bottom of the page and clicking past events
